version: "3"

services:
  zookeeper:
    image: netflixoss/exhibitor:1.5.2
    hostname: zookeeper
    ports:
      - "2181:2181"
      - "8989:8080"
    networks:
      vamp:
        ipv4_address: 172.16.121.2

  mesos-master:
    image: mesosphere/mesos-master:1.2.1
    privileged: true
    hostname: localhost
    ports:
      - "5050:5050"
    networks:
      vamp:
        ipv4_address: 172.16.121.3
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      MESOS_ZK: zk://zookeeper:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: vamp
      MESOS_HOSTNAME: 192.168.65.2
      MESOS_WORK_DIR: /var/tmp/mesos
      MESOS_LOG_DIR: /var/log/mesos
      LIBPROCESS_IP: 172.16.121.3

  mesos-slave:
    image: mesosphere/mesos-slave:1.2.1
    privileged: true
    hostname: localhost
    ports:
      - "5051:5051"
    networks:
      vamp:
        ipv4_address: 172.16.121.4
    links:
      - zookeeper:zookeeper
      - mesos-master:master.mesos
    depends_on:
      - zookeeper
      - mesos-master
    environment:
      MESOS_MASTER: zk://zookeeper:2181/mesos
      MESOS_CONTAINERIZERS: docker
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_HOSTNAME: 192.168.65.2
      MESOS_WORK_DIR: /var/tmp/mesos
      MESOS_LOG_DIR: /var/log/mesos
      LIBPROCESS_IP: 172.16.121.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  marathon:
    image: mesosphere/marathon:v1.3.10
    entrypoint:
      - ./bin/start
      - --disable_ha
      - --http_port=8090
    hostname: localhost
    ports:
     - "8090:8090"
    networks:
      vamp:
        ipv4_address: 172.16.121.5
    links:
      - zookeeper
      - mesos-master
    depends_on:
      - zookeeper
      - mesos-master
      - mesos-slave
    environment:
      - MARATHON_ZK=zk://zookeeper:2181/marathon
      - MARATHON_MASTER=zk://zookeeper:2181/mesos
      - LIBPROCESS_IP=172.16.121.5

  mysql:
    image: mysql:5
    hostname: mysql
    ports:
      - "3306:3306"
    networks:
      vamp:
        ipv4_address: 172.16.121.6
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      vamp:
        ipv4_address: 172.16.121.7
    environment:
      - cluster.name=vamp
      - discovery.type=single-node
      - xpack.security.enabled=false

#  kibana:
#    image: docker.elastic.co/kibana/kibana:5.6.2
#    hostname: kibana
#    ports:
#      - "5601:5601"
#    networks:
#      vamp:
#        ipv4_address: 172.16.121.8

networks:
  vamp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.121.0/24
